#!/bin/sh
#
# Note runlevel 2345, 86 is the Start order and 85 is the Stop order
#
# chkconfig: 2345 86 85
# description: Description of the Service
#
# Below is the source function library, leave it be
. /etc/init.d/functions

# result of whereis forever or whereis node
export PATH=$PATH:/usr/bin  
# result of whereis node_modules
export NODE_PATH=$NODE_PATH:/usr/lib/node_modules

start(){  
        forever --pidFile pid_3000.pid start /core/ehotel/service/app/service_modules/server_3000.js
}

stop(){  
        forever stop /core/ehotel/service/app/service_modules/server_3000.js
}

restart(){  
        forever restart /core/ehotel/service/app/service_modules/server_3000.js
}

case "$1" in  
        start)
                echo "Start Service 3000"
                start
                ;;
        stop)
                echo "Stop Service 3000"
                stop
                ;;
        restart)
                echo "Restart Service 3000"
                restart
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
                ;;
esac 